-- ==================== Database Schema for License System ====================
-- Database: Cloudflare D1 (SQLite)

-- Licenses table
CREATE TABLE IF NOT EXISTS licenses (
  license_key TEXT PRIMARY KEY,           -- Format: XXXXX-XXXXX-XXXXX-XXXXX
  device_id TEXT,                         -- Device ID (set on activation)
  session_token TEXT,                     -- Session token (generated on activation)
  nonce TEXT NOT NULL,                    -- Current nonce (SERVER-GENERATED!)
  nonce_timestamp INTEGER NOT NULL,       -- When nonce was last updated (SERVER TIME!)
  status TEXT DEFAULT 'active',           -- 'active' | 'burned' | 'expired'
  created_at INTEGER NOT NULL,            -- License creation time (milliseconds)
  expires_at INTEGER,                     -- Expiration time (NULL = no expiration)
  last_verified INTEGER,                  -- Last verification time
  verification_count INTEGER DEFAULT 0    -- Number of verifications
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_device_id ON licenses(device_id);
CREATE INDEX IF NOT EXISTS idx_session_token ON licenses(session_token);
CREATE INDEX IF NOT EXISTS idx_status ON licenses(status);
CREATE INDEX IF NOT EXISTS idx_nonce_timestamp ON licenses(nonce_timestamp);

-- ==================== IMPORTANT NOTES ====================

-- 1. NONCE SECURITY:
--    - nonce is generated by SERVER, not client
--    - nonce_timestamp is SERVER time, NOT client time
--    - Client CANNOT manipulate time to bypass nonce validation
--    - Each verification generates NEW nonce

-- 2. TIME-BASED SECURITY:
--    - All timestamps use server time (Date.now() in Cloudflare Worker)
--    - Client time is NEVER trusted
--    - Nonce age is calculated using: (SERVER_NOW - nonce_timestamp)
--    - Max nonce age: 24 hours (configurable)

-- 3. STATUS VALUES:
--    - 'active': License is valid and can be used
--    - 'burned': License has been revoked (security breach or abuse)
--    - 'expired': License has expired (expires_at < now)

-- ==================== EXAMPLE DATA ====================

-- Insert example license (for testing)
INSERT INTO licenses (
  license_key,
  nonce,
  nonce_timestamp,
  status,
  created_at,
  expires_at
) VALUES (
  'TEST1-TEST2-TEST3-TEST4',
  'INITIAL_NONCE_32_CHARS_RANDOM',
  1234567890000,
  'active',
  1234567890000,
  NULL  -- No expiration
);

-- ==================== QUERIES ====================

-- Get license by key
-- SELECT * FROM licenses WHERE license_key = 'XXXXX-XXXXX-XXXXX-XXXXX';

-- Get all active licenses
-- SELECT * FROM licenses WHERE status = 'active';

-- Get expired licenses (based on server time)
-- SELECT * FROM licenses WHERE expires_at IS NOT NULL AND expires_at < strftime('%s','now') * 1000;

-- Burn a license
-- UPDATE licenses SET status = 'burned' WHERE license_key = 'XXXXX-XXXXX-XXXXX-XXXXX';

-- Get verification statistics
-- SELECT license_key, verification_count, last_verified FROM licenses ORDER BY verification_count DESC;

-- Clean up old nonces (older than 30 days)
-- DELETE FROM licenses WHERE nonce_timestamp < (strftime('%s','now') * 1000 - 30*24*60*60*1000) AND status != 'active';
